"""
Packet capture helpers for signature collectors.

This module uses tcpdump to capture traffic into a pcap file and Scapy to
inspect packets and extract the UDP payload. It is intentionally minimal and
focused on "one-shot" captures for a single request.

Requirements:
- tcpdump installed on the host (apt-get install tcpdump).
- scapy installed in the Python environment (declared in pyproject.toml).
"""

from __future__ import annotations

import subprocess
import tempfile
import time
from pathlib import Path
from typing import Callable, List, Optional, Tuple

from scapy.all import PcapReader  # type: ignore[import]
from scapy.layers.inet import IP, UDP  # type: ignore[import]
from scapy.layers.inet6 import IPv6  # type: ignore[import]

# * (payload, src_ip, sport, dst_ip, dport)
UdpPacketInfo = Tuple[bytes, str, int, str, int]


class CaptureError(RuntimeError):
    """Raised when capture fails or no suitable packet is found."""


def capture_single_udp_payload(
    bpf_filter: str,
    iface: Optional[str] = None,
    timeout: int = 5,
) -> bytes:
    """
    Capture a single UDP packet matching the BPF filter and return its payload.

    Parameters:
        bpf_filter: tcpdump BPF filter string, e.g. "udp and port 53".
        iface: network interface name (None = tcpdump default).
        timeout: overall timeout in seconds.

    Returns:
        Raw UDP payload (bytes).

    Raises:
        CaptureError if tcpdump is missing, times out, or no packet matches.
    """

    with tempfile.TemporaryDirectory() as tmpdir:
        pcap_path = Path(tmpdir) / "capture.pcap"

        cmd = ["tcpdump", "-w", str(pcap_path), "-U", "-n"]
        if iface:
            cmd.extend(["-i", iface])
        cmd.append(bpf_filter)

        try:
            proc = subprocess.Popen(
                cmd,
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
            )
        except FileNotFoundError as exc:
            raise CaptureError("tcpdump not found on PATH; please install it.") from exc

        try:
            # Give tcpdump a moment to start listening.
            time.sleep(0.5)

            # Wait up to `timeout` seconds for some traffic to be captured.
            start = time.time()
            while time.time() - start < timeout:
                if pcap_path.exists() and pcap_path.stat().st_size > 24:  # pcap header ~24 bytes
                    break
                time.sleep(0.2)

        finally:
            # Stop tcpdump regardless of success/failure.
            proc.terminate()
            try:
                proc.wait(timeout=2)
            except subprocess.TimeoutExpired:
                proc.kill()

        if not pcap_path.exists() or pcap_path.stat().st_size <= 24:
            raise CaptureError("No packets captured; try increasing timeout or adjusting filter.")

        # Read first UDP packet and return its payload.
        with PcapReader(str(pcap_path)) as reader:
            for pkt in reader:
                if UDP in pkt and (IP in pkt or IPv6 in pkt):
                    udp_layer = pkt[UDP]
                    payload = bytes(udp_layer.payload)
                    if payload:
                        return payload

        raise CaptureError("Captured pcap has no UDP payload matching the filter.")


def _read_udp_packets_from_pcap(pcap_path: Path) -> List[UdpPacketInfo]:
    """Read all UDP packets from a pcap file; returns (payload, src_ip, sport, dst_ip, dport)."""
    result: List[UdpPacketInfo] = []
    with PcapReader(str(pcap_path)) as reader:
        for pkt in reader:
            if UDP not in pkt or not (IP in pkt or IPv6 in pkt):
                continue
            udp = pkt[UDP]
            payload = bytes(udp.payload)
            if not payload:
                continue
            ip_layer = pkt[IP] if IP in pkt else pkt[IPv6]
            src_ip = str(ip_layer.src)
            dst_ip = str(ip_layer.dst)
            result.append((payload, src_ip, udp.sport, dst_ip, udp.dport))
    return result


def capture_udp_payloads_with_trigger(
    bpf_filter: str,
    trigger: Callable[[], None],
    iface: Optional[str] = None,
    timeout: int = 5,
    *,
    post_trigger_wait: float = 1.0,
) -> List[UdpPacketInfo]:
    """
    Start tcpdump, run trigger (e.g. HTTP/3 request), then return all captured
    UDP packets as (payload, src_ip, sport, dst_ip, dport).

    Use this when the traffic is generated by the trigger (e.g. curl) rather
    than external traffic. Caller can then pick the first \"client\" packet
    (src_ip == local_ip) or "server" packet (dst_ip == local_ip).
    """
    with tempfile.TemporaryDirectory() as tmpdir:
        pcap_path = Path(tmpdir) / "capture.pcap"
        cmd = ["tcpdump", "-w", str(pcap_path), "-U", "-n"]
        if iface:
            cmd.extend(["-i", iface])
        cmd.append(bpf_filter)

        try:
            proc = subprocess.Popen(
                cmd,
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
            )
        except FileNotFoundError as exc:
            raise CaptureError("tcpdump not found on PATH; please install it.") from exc

        try:
            time.sleep(0.5)
            trigger()
            dwell = max(post_trigger_wait, 0.3)
            deadline = time.time() + dwell
            while time.time() < deadline:
                time.sleep(0.1)
        finally:
            proc.terminate()
            try:
                proc.wait(timeout=2)
            except subprocess.TimeoutExpired:
                proc.kill()

        if not pcap_path.exists() or pcap_path.stat().st_size <= 24:
            raise CaptureError(
                "No packets captured; trigger may have produced no matching traffic."
            )

        return _read_udp_packets_from_pcap(pcap_path)

